<a href="https://colab.research.google.com/github/pranuk050-pixel/Python_learning-consepts/blob/main/04-08-26%20Pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Pandas ===> numpy array
### wrapper on top numpy array

In [ ]:
pandas ==>panel datasets, python for data analysis

In [ ]:
#### Summary of the information
### Descriptive statistics
### Visualizations(Graphs)
#### Matplotlib
### Seaborn
### plotly (Realtime Usecases)
### Streamlit (Dashboards) + (Realtime Usecases)

In [ ]:
Analysis of data
Visualization of data

In [ ]:
import pandas as pd

In [ ]:
### Rich in built data reading capacity with built in functions
### xml,json,html, csv, excel, parquet
### oracle,sql server ,postgree sql, == > connect to these with an external package support
### Dataframe

In [ ]:
pd.DataFrame([1,2,3])

   0
0  1
1  2
2  3

In [ ]:
import numpy as np
data=np.random.randint(0,10,(3,3))
df=pd.DataFrame(data,columns=[['A','B','C']],index=['x','y','z'])

In [ ]:
df

   A  B  C
x  9  5  8
y  8  9  8
z  7  7  4

In [ ]:
data

array([[9, 5, 8],
       [8, 9, 8],
       [7, 7, 4]])

In [ ]:
### retail example
### 10 retail stores
### sales, units, gross profilt, promotions

In [ ]:
data=np.random.randint(0,100,(10,5))
store_names=["store "+str(i) for i in range(1,11)]
column="Sales, units, gross profilt, promotions,trasactions".split(",")

In [ ]:
column

['Sales', ' units', ' gross profilt', ' promotions', 'trasactions']

In [ ]:
retail_dataset=pd.DataFrame(data,columns=column,index=store_names)

In [ ]:
retail_dataset.to_csv('sample.csv')

In [ ]:
retail_dataset.iloc[3:5,2:3]

         gross profilt
store 4             88
store 5             65

In [ ]:
retail_dataset.iloc[0:3,4:6]

         trasactions
store 1           87
store 2           95
store 3           32

In [ ]:
retail_dataset.iloc[3:6,3:5]

          promotions  trasactions
store 4           57           29
store 5           51           29
store 6           38           69

In [ ]:
retail_dataset.iloc[-3:-1,-3:-1]

         gross profilt  promotions
store 8             75          41
store 9             52           4

In [ ]:
retail_dataset

          Sales   units   gross profilt   promotions  trasactions
store 1      98      61              33           13           87
store 2      40      92              89           20           95
store 3      26       7              19           72           32
store 4      24      21              88           57           29
store 5      33       8              65           51           29
store 6      88      86              43           38           69
store 7       3       3              67           30           85
store 8      71      57              75           41           92
store 9      58      13              52            4           14
store 10     57      47              24           56           78

In [ ]:
retail_dataset.iloc[-4:-2,0:2]

         Sales   units
store 7      3       3
store 8     71      57

In [ ]:
retail_dataset.shape

(10, 5)

In [ ]:
retail_subset=retail_dataset.iloc[0:5,]

In [ ]:
retail_subset

In [ ]:
retail_subset.iloc[0:2,:]

         Sales   units   gross profilt   promotions  trasactions
store 1     98      61              33           13           87
store 2     40      92              89           20           95

In [ ]:
retail_subset.loc[["store 1","store 3"],:]

         Sales   units   gross profilt   promotions  trasactions
store 1     98      61              33           13           87
store 3     26       7              19           72           32

In [ ]:
retail_subset.loc["store 1","Sales"]

np.int64(98)

In [ ]:
retail_dataset.sum(axis=0)

Sales             498
 units            395
 gross profilt    555
 promotions       382
trasactions       610
dtype: int64

In [ ]:
retail_dataset.sum(axis=0)

Sales             498
 units            395
 gross profilt    555
 promotions       382
trasactions       610
dtype: int64

In [ ]:
retail_dataset.sum()

Sales             498
 units            395
 gross profilt    555
 promotions       382
trasactions       610
dtype: int64

In [ ]:
retail_dataset.min(axis=1)

store 1     13
store 2     20
store 3      7
store 4     21
store 5      8
store 6     38
store 7      3
store 8     41
store 9      4
store 10    24
dtype: int64

In [ ]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/Home Credit Analysis/application_train.csv")

In [ ]:
df.shape

(307511, 122)

In [ ]:
[i for i in df.columns]

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [ ]:
df.shape

(307511, 122)

In [ ]:
df.index

RangeIndex(start=0, stop=307511, step=1)

In [ ]:
df.values

array([[100002, 1, 'Cash loans', ..., 0.0, 0.0, 1.0],
       [100003, 0, 'Cash loans', ..., 0.0, 0.0, 0.0],
       [100004, 0, 'Revolving loans', ..., 0.0, 0.0, 0.0],
       ...,
       [456253, 0, 'Cash loans', ..., 1.0, 0.0, 1.0],
       [456254, 1, 'Cash loans', ..., 0.0, 0.0, 0.0],
       [456255, 0, 'Cash loans', ..., 2.0, 0.0, 1.0]], dtype=object)

In [ ]:
df.dtypes

SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     float64
AMT_REQ_CREDIT_BUREAU_WEEK    float64
AMT_REQ_CREDIT_BUREAU_MON     float64
AMT_REQ_CREDIT_BUREAU_QRT     float64
AMT_REQ_CREDIT_BUREAU_YEAR    float64
Length: 122, dtype: object

In [ ]:
df_subset=df.iloc[0:10,0:10]

In [ ]:
df_subset

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5
5,100008,0,Cash loans,M,N,Y,0,99000.0,490495.5,27517.5
6,100009,0,Cash loans,F,Y,Y,1,171000.0,1560726.0,41301.0
7,100010,0,Cash loans,M,Y,Y,0,360000.0,1530000.0,42075.0
8,100011,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5
9,100012,0,Revolving loans,M,N,Y,0,135000.0,405000.0,20250.0

In [ ]:
df_subset.describe(include='all')

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY
count,10.000000,10.000000,10,10,10,10,10.000000,10.000000,1.000000e+01,10.000000
unique,NaN,NaN,2,2,2,2,NaN,NaN,NaN,NaN
top,NaN,NaN,Cash loans,M,N,Y,NaN,NaN,NaN,NaN
freq,NaN,NaN,8,6,7,9,NaN,NaN,NaN,NaN
mean,100007.200000,0.100000,NaN,NaN,NaN,NaN,0.100000,167400.000000,7.666614e+05,28367.100000
std,3.425395,0.316228,NaN,NaN,NaN,NaN,0.316228,88660.024814,5.334290e+05,10698.444775
min,100002.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,67500.000000,1.350000e+05,6750.000000
25%,100004.500000,0.000000,NaN,NaN,NaN,NaN,0.000000,114750.000000,4.053994e+05,22574.250000
50%,100007.500000,0.000000,NaN,NaN,NaN,NaN,0.000000,135000.000000,5.017478e+05,28602.000000
75%,100009.750000,0.000000,NaN,NaN,NaN,NaN,0.000000,194625.000000,1.225029e+06,35230.500000
max,100012.000000,1.000000,NaN,NaN,NaN,NaN,1.000000,360000.000000,1.560726e+06,42075.000000

In [ ]:
df_subset['NAME_CONTRACT_TYPE']

0         Cash loans
1         Cash loans
2    Revolving loans
3         Cash loans
4         Cash loans
5         Cash loans
6         Cash loans
7         Cash loans
8         Cash loans
9    Revolving loans
Name: NAME_CONTRACT_TYPE, dtype: object

In [ ]:
df.head(2)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.tail(2)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
307509,456254,1,Cash loans,F,N,Y,0,171000.0,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.0,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [ ]:
subdf.mean()

KeyboardInterrupt: